### ISSUE TITLE
event system missing mono script

### ISSUE THREAD

**Issue by ezavesky** [EnoxSoftware/GoogleVRWithOpenCVForUnityExample#1]
From latest branch, when trying to build for android (or even just loading), the script is missing that should be tied to the object EventSystem.
![image](https://cloud.githubusercontent.com/assets/12480297/25765768/44883c00-31b4-11e7-9cac-f7ca58bf8f3e.png)

**Comment by EnoxSoftware** [comment]
Thank you for posting the issue.
We have created a "[dev_gvr-unity-sdk_1.40.0 branch](https://github.com/EnoxSoftware/GoogleVRWithOpenCVForUnityExample/tree/dev_gvr-unity-sdk_1.40.0)" supporting the new GVR SDK.

**Comment by megmaltese** [comment]
I am having this problem.
What script should go in there???
