### ISSUE TITLE
trouble compiling with modern version of GVR

### ISSUE THREAD

**Issue by ezavesky** [EnoxSoftware/GoogleVRWithOpenCVForUnityExample#2]
Found a few compile bugs for 1.40 version of GVR sdk.  Additionally, when fixed, couldn't find a great working condition...
* neither the preview in the desktop works, just stays as static/fixed image
* nor does the android install, it appears as if the quad is highly zoomed
* Also, using your pre-compiled version, it seemed that all image content was seen through a fish-eye effect.  Is this normal or how all content will be rendered to approximate a 3d setting?

(super-zoomed quad extents)
![20170505_170318_resized](https://cloud.githubusercontent.com/assets/12480297/25765968/6546942c-31b5-11e7-9092-eaaba47d1072.jpg)

(perspective of menu/GUI versus image)
![20170505_170329_resized](https://cloud.githubusercontent.com/assets/12480297/25765981/73a45bd0-31b5-11e7-8b64-585ec89e4bd5.jpg)

([fisheye effect](https://en.wikipedia.org/wiki/Fisheye_lens) )
![20170505_171049_resized](https://cloud.githubusercontent.com/assets/12480297/25766103/12ff38bc-31b6-11e7-87a4-58c1ec73b5a5.jpg)

**Comment by EnoxSoftware** [comment]
Thank you for posting the issue.
We have created a "[dev_gvr-unity-sdk_1.40.0 branch](https://github.com/EnoxSoftware/GoogleVRWithOpenCVForUnityExample/tree/dev_gvr-unity-sdk_1.40.0)" supporting the new GVR SDK.
