### ISSUE TITLE
Doesnt work with latest Google VR sdk

### ISSUE THREAD

**Issue by Zumbalamambo** [EnoxSoftware/GoogleVRWithOpenCVForUnityExample#5]
please fix the issue with GVRMain? It isn't possible to run this app.

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.

Could you tell me the environment you tested?
Unity version : 
OpenCVForUnity version : 
GVR Unity SDK version :

**Comment by Zumbalamambo** [comment]
OpenCVForUnity v 2.4.4
GVR SDK for Unity v1.190.1
unity v 2018.3

**Comment by Zumbalamambo** [comment]
@EnoxSoftware  any updates?

**Comment by EnoxSoftware** [comment]
I have just updated the example project.
